name: CI

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Install dependencies
        run: |
          composer install
          vendor/bin/simple-phpunit install

      - name: "Run PHPStan analysis"
        run: vendor/bin/phpstan analyse